"""The role apply must follow a slot upgrade (#1203).

The heartbeat skips ``apply_role_assignment`` while nothing it would send has
changed since the last successful apply. It used to key that skip on the
rendered role env alone. The role env carries only role-scoped values
(profiles, groups, engine, agent keys), never the image tag, and the stamp lives
in the persistent state dir. So after a slot upgrade the new release's
supervisor skipped the apply from its first heartbeat, and the agent
DaemonSets kept the previous release's chart and images until a role next
changed. On a real 2026.09.04-1 -> nightly-20260924 upgrade they stayed on
2026.09.04-1 for 20 minutes with the new supervisor running; removing only the
stamp moved them within 26 s.

The key now also covers the image tag and the chart the apply renders. Those
change only with a slot upgrade, so steady-state heartbeats still skip.
"""

from __future__ import annotations

import hashlib
import inspect
from pathlib import Path

import pytest

from spatium_supervisor import heartbeat, service_lifecycle

ROLE_ENV = (
    "# Auto-generated by spatium-supervisor — do not hand-edit.\n"
    "COMPOSE_PROFILES=dhcp,dns-bind9\n"
    "AGENT_GROUP=default\n"
    "DNS_ENGINE=bind9\n"
    "DHCP_AGENT_GROUP=default\n"
    "DHCP_NETWORK_MODE=host\n"
)

OLD_TAG = "2026.09.04-1"
NEW_TAG = "nightly-20260924"


@pytest.fixture
def slot(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    """A state dir, a rendered role env and a baked chart, on the old slot."""
    chart = tmp_path / "spatiumddi-appliance.tgz"
    chart.write_bytes(b"chart bytes of the old slot")
    monkeypatch.setattr(service_lifecycle, "_BAKED_CHART_TARBALL", chart)
    monkeypatch.setattr(service_lifecycle, "_chart_digest_cache", None)
    monkeypatch.setenv("SPATIUMDDI_VERSION", OLD_TAG)
    state_dir = tmp_path / "state"
    state_dir.mkdir()
    env_path = state_dir / "role-compose.env"
    env_path.write_text(ROLE_ENV, encoding="utf-8")

    class Slot:
        pass

    s = Slot()
    s.chart, s.state_dir, s.env_path = chart, state_dir, env_path
    return s


def _stamp_a_successful_apply(slot) -> None:
    """What the heartbeat does after an apply that returned ready."""
    due, key = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due
    heartbeat._write_last_apply_hash(slot.state_dir, key)


def test_steady_state_still_skips_the_apply(slot) -> None:
    """The reason the skip exists: nothing changed, nothing is re-applied."""
    _stamp_a_successful_apply(slot)
    due, _ = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due is False


def test_the_first_heartbeat_on_a_new_slot_reapplies_the_role_release(
    monkeypatch: pytest.MonkeyPatch, slot
) -> None:
    """REGRESSION (#1203): same role env, new slot. The upgrade re-stamps
    SPATIUMDDI_VERSION in the host .env and bakes a new chart; the apply must
    run once so the agents move to the new release."""
    _stamp_a_successful_apply(slot)
    monkeypatch.setenv("SPATIUMDDI_VERSION", NEW_TAG)
    slot.chart.write_bytes(b"chart bytes of the new slot")
    due, key = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due is True
    heartbeat._write_last_apply_hash(slot.state_dir, key)
    due_again, _ = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due_again is False, "once applied on the new slot, steady state skips again"


def test_a_new_image_tag_alone_reapplies(monkeypatch: pytest.MonkeyPatch, slot) -> None:
    _stamp_a_successful_apply(slot)
    monkeypatch.setenv("SPATIUMDDI_VERSION", NEW_TAG)
    due, _ = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due is True


def test_a_new_chart_alone_reapplies(monkeypatch: pytest.MonkeyPatch, slot) -> None:
    """A chart change on the same tag (templates, key gating) must land too."""
    _stamp_a_successful_apply(slot)
    slot.chart.write_bytes(b"the same tag, different templates")
    due, _ = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due is True


def test_a_stamp_from_a_supervisor_that_keyed_on_the_env_alone_reapplies_once(
    slot,
) -> None:
    """Upgrading FROM a release with the old key: its stamp is sha256(env)."""
    legacy = hashlib.sha256(ROLE_ENV.encode("utf-8")).hexdigest()
    heartbeat._write_last_apply_hash(slot.state_dir, legacy)
    due, _ = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due is True


def test_a_role_change_still_reapplies(slot) -> None:
    _stamp_a_successful_apply(slot)
    changed = ROLE_ENV.replace("dhcp,dns-bind9", "dhcp")
    due, _ = heartbeat._role_apply_due(slot.state_dir, changed, slot.env_path)
    assert due is True


def test_the_key_and_the_values_read_the_same_image_tag(monkeypatch: pytest.MonkeyPatch) -> None:
    """One definition: the key can never describe a tag the apply does not render."""
    monkeypatch.setenv("SPATIUMDDI_VERSION", NEW_TAG)
    env_vars = {"CONTROL_PLANE_URL": "https://cp.example"}
    values = service_lifecycle._build_values(["dns-bind9"], env_vars)
    assert values["global"]["imageTag"] == service_lifecycle.role_image_tag(env_vars) == NEW_TAG


def test_an_unreadable_chart_does_not_break_the_key(slot) -> None:
    """The apply itself reports the unreadable chart as failed (and stamps
    nothing); the key must still be computable."""
    slot.chart.unlink()
    due, key = heartbeat._role_apply_due(slot.state_dir, ROLE_ENV, slot.env_path)
    assert due is True and len(key) == 64


def test_the_heartbeat_takes_its_skip_decision_from_the_full_key() -> None:
    """The heartbeat must decide through ``_role_apply_due``, never by hashing
    the rendered env on its own again."""
    src = inspect.getsource(heartbeat.heartbeat_once)
    assert "_role_apply_due(" in src
    assert "hashlib.sha256(rendered" not in src
