"""Operator Copilot tool registry — re-export the shared registry +
trigger tool registration on import.

Import this module from anywhere that needs to dispatch tools (the
chat orchestrator in Wave 3, the MCP endpoint in Wave 2). The
side-effect imports below register every read-only tool.
"""

# Side-effect imports — each module's @register_tool decorators run on
# import and populate ``REGISTRY``.
from app.services.ai.tools import (  # noqa: F401, E402
    admin,
    appliance,
    apt,
    auth_grants,
    av,
    backup,
    bacnet,
    bgp,
    bgp_lg,
    bgp_monitor,
    block_sync,
    branding,
    certificates,
    changes,
    conformity,
    copilot,
    cutover,
    dhcp,
    diagnostics,
    dicom,
    dns,
    dns_threat,
    dnsbl,
    e911,
    firewall,
    imports,
    integrations,
    ipam,
    lldp,
    maintenance,
    multicast,
    nettools,
    network,
    network_modeling,
    new_devices,
    nmap,
    ntp,
    observability,
    ops,
    ot,
    ownership,
    pairing,
    pcap,
    proposals,
    provisioning_requests,
    radvd,
    redis,
    reports,
    resolver,
    saved_views,
    services,
    snmp,
    ssh,
    support_bundle,
    syslog,
    tls_certs,
    upgrades,
    vendor,
    webhooks,
    whois,
    wol_scheduler,
)
from app.services.ai.tools.base import (
    REGISTRY,
    Tool,
    ToolArgumentError,
    ToolDisabled,
    ToolNotFound,
    ToolPermissionDenied,
    ToolRegistry,
    effective_tool_names,
    register_tool,
)

__all__ = [
    "REGISTRY",
    "Tool",
    "ToolRegistry",
    "ToolNotFound",
    "ToolArgumentError",
    "ToolDisabled",
    "ToolPermissionDenied",
    "register_tool",
    "effective_tool_names",
]
