#!/usr/bin/env python3
"""Regenerate backend/app/data/release_schema_heads.json from the git tags (#1227).

For every release tag, read the Alembic migration files as they were at that
tag and record the tree's single head. A newer release uses the table to tell
whether an older release it is being rolled back or downgraded to can run on
the current database; see ``app/services/upgrades/schema_rollback.py``.

Releases record their own head in the ``release_schema_head`` table when they
start, so this file only has to cover what that table cannot: releases older
than it, and releases this database never ran. Refreshing it at release prep
keeps the second case covered; a stale file is not wrong, it just answers
"unknown" for the newest releases.

    python3 scripts/release_schema_heads.py            # print the table
    python3 scripts/release_schema_heads.py --write    # rewrite the JSON file
    python3 scripts/release_schema_heads.py --check    # exit 1 if the file is stale

Reads git objects only (never the working tree), and parses migration files
with ``ast`` rather than importing them, so it runs on any Python 3.9+ with
no dependencies.
"""

from __future__ import annotations

import argparse
import ast
import io
import json
import re
import subprocess
import sys
import tarfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "backend" / "app" / "data" / "release_schema_heads.json"
VERSIONS_DIR = "backend/alembic/versions"

# CalVer releases until 1.0.0, SemVer from then on (#1182). Nightly and
# pre-release tags are left out: nightlies are versioned 0.0.0-<date>+<sha>
# and record themselves at runtime.
_RELEASE_TAG = re.compile(r"^(\d{4}\.\d{2}\.\d{2}-\d+|\d+\.\d+\.\d+)$")


def _git(*args: str) -> bytes:
    return subprocess.run(["git", *args], cwd=REPO, check=True, capture_output=True).stdout


def _release_tags() -> list[str]:
    tags = _git("tag", "-l").decode().split()
    return [t for t in tags if _RELEASE_TAG.match(t)]


def _literal(node: ast.AST) -> object:
    try:
        return ast.literal_eval(node)
    except ValueError:
        return None


def _parse_revision(source: str) -> tuple[str | None, tuple[str, ...]]:
    """``(revision, down_revisions)`` from a migration file's module-level assigns."""
    revision: str | None = None
    down: tuple[str, ...] = ()
    for node in ast.parse(source).body:
        # Both ``revision = "x"`` and ``revision: str = "x"`` occur in the tree.
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target, value = node.targets[0], node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            target, value = node.target, node.value
        else:
            continue
        if not isinstance(target, ast.Name):
            continue
        if target.id == "revision":
            val = _literal(value)
            revision = val if isinstance(val, str) else None
        elif target.id == "down_revision":
            val = _literal(value)
            if isinstance(val, str):
                down = (val,)
            elif isinstance(val, (tuple, list)):
                down = tuple(v for v in val if isinstance(v, str))
    return revision, down


def heads_at(ref: str) -> list[str]:
    """The Alembic head(s) of the migration tree as it was at ``ref``."""
    try:
        archive = _git("archive", ref, VERSIONS_DIR)
    except subprocess.CalledProcessError:
        return []
    revisions: set[str] = set()
    referenced: set[str] = set()
    with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
        for member in tar.getmembers():
            if not member.isfile() or not member.name.endswith(".py"):
                continue
            handle = tar.extractfile(member)
            if handle is None:
                continue
            rev, down = _parse_revision(handle.read().decode("utf-8"))
            if rev:
                revisions.add(rev)
                referenced.update(down)
    return sorted(revisions - referenced)


def build() -> dict[str, str]:
    table: dict[str, str] = {}
    for tag in _release_tags():
        heads = heads_at(tag)
        if len(heads) == 1:
            table[tag] = heads[0]
        else:
            # A tag with two heads never shipped a runnable migrate step, and
            # one with none predates Alembic; neither has an answer to give.
            print(f"skipping {tag}: {len(heads)} heads {heads}", file=sys.stderr)
    return dict(sorted(table.items()))


def render(table: dict[str, str]) -> str:
    doc = {
        "_comment": (
            "The Alembic head each SpatiumDDI release was built with (#1227). "
            "Generated by scripts/release_schema_heads.py from the release tags; "
            "do not edit by hand."
        ),
        "releases": table,
    }
    return json.dumps(doc, indent=2) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help=f"rewrite {OUT.relative_to(REPO)}")
    mode.add_argument("--check", action="store_true", help="exit 1 when the file is stale")
    args = parser.parse_args()

    text = render(build())
    if args.write:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(REPO)}")
        return 0
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(
                f"{OUT.relative_to(REPO)} is stale: run "
                "`python3 scripts/release_schema_heads.py --write`",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(REPO)} is current")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
